SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS MangoMDB;
CREATE SCHEMA MangoMDB;
USE MangoMDB;

CREATE TABLE User (
  UserId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  UserName VARCHAR(45) NOT NULL,
  UserAccount VARCHAR(100) NOT NULL,
  UserPassword VARCHAR(45) NOT NULL,
  PRIMARY KEY (UserId),
  UNIQUE (UserAccount)
  )ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
