SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS MangoMDB;
CREATE SCHEMA MangoMDB;
USE MangoMDB;

CREATE TABLE User (
    UserId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    UserName VARCHAR(45) NOT NULL,
    UserAccount VARCHAR(100) NOT NULL,
    UserPassword VARCHAR(45) NOT NULL,
    PRIMARY KEY (UserId),
    UNIQUE (UserAccount)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE Item (
    ItemId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ItemName VARCHAR(100) NOT NULL,
    ProducerId SMALLINT UNSIGNED,
    SellerId SMALLINT UNSIGNED,
    Amount INT UNSIGNED NOT NULL,
    Unit VARCHAR(50),
    Price DECIMAL NOT NULL,
    PRIMARY KEY (ItemId),
    UNIQUE (ItemName)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE OrderHistory (
    OrderId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    UserId SMALLINT UNSIGNED NOT NULL,
    OrderDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (OrderId),
    KEY idx_FK_UserId (UserId),
    CONSTRAINT FK_Order_User FOREIGN KEY (UserId) REFERENCES User (UserId) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE OrderDetail (
    OrderId SMALLINT UNSIGNED NOT NULL,
    ItemId SMALLINT UNSIGNED NOT NULL,
    Amount INT NOT NULL,
    PRIMARY KEY  (OrderId,ItemId),
    KEY idx_FK_OrderId (OrderId),
    KEY idx_FK_ItemId (ItemId),
    CONSTRAINT FK_OrderDetail_OrderHistory FOREIGN KEY (OrderId) REFERENCES OrderHistory (OrderId) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_OrderDetail_Item FOREIGN KEY (ItemId) REFERENCES Item (ItemId) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
